### ISSUE TITLE
Use the Validating event and an errorProvider instead of custom

### ISSUE THREAD

**Issue by lightinasnowstorm** [DrWhoCares/TranslationScriptTools#12]
Use the Validating event to validate the inputs on the various fields
As well, use an error provider to show the error on the specific component
rather than calling on text change and using a label for errors, as the label can be not-as-specific

**Comment by DrWhoCares** [comment]
Fixed in https://github.com/DrWhoCares/TranslationScriptTools/releases/tag/v1.2019.7.4
3a9b8af6f7dbb9f8074f02bb1bcf507ce3422e33
May further implement this on the script creator/editor side, but I may just refactor that entire mess later.
